const TextSection = ({
    idx,
    textString,
}: {
    idx: number;
    textString?: string;
}) => {
    return (
        <div className="flex m-4">
            <p className="font-bold text-3xl p-2">{idx}</p>
            <p>
                {textString ??
                    "Connect with us and we will share a form for you to fill out."}
            </p>
        </div>
    );
};

const FAQs = () => {
    return (
        <section className="grid grid-cols-12 bg-slate-100 p-8 rounded-md w-[800px]">
            <div className="flex col-span-3 text-xl text-right font-bold flex-col rounded-md bg-slate-50 p-4">
                How it works
            </div>
            <div className="col-span-9 " id="text-=section">
                <TextSection
                    idx={1}
                    textString="We will work with you to define your purpose, answer question and fill in the detail that would go into the form."
                />
                <TextSection
                    idx={2}
                    textString="We will breakdown your tasks in 80/20, 80% will be taken care of by our trained humans, while 20% will be generated by your team to supervise our 80%"
                />
                <TextSection
                    idx={3}
                    textString="We will use your data and train your proprietary reward model, and then use it to finetune an open-source LLM for you"
                />
                <TextSection
                    idx={4}
                    textString="We will then deploy the LLM and your reward model on our servers, and you can use our API to connect to it."
                />
            </div>
        </section>
    );
};

export default FAQs;
